### ISSUE TITLE
Tests failed in 1.12.0-devel-py3 docker

### ISSUE THREAD

**Issue by zou000** [tensorflow/custom-op#5]
It seems that `resource_loader.get_path_to_datafile` is returning wrong directory. I did not try any other ways to build.

```
15:41 $ docker run -it -v ~/git/custom-op:/home/custom-op tensorflow/tensorflow:1.12.0-devel-py3 /bin/bash
root@52727958a85b:~# ls
root@52727958a85b:~# cd /home/custom-op/
root@52727958a85b:/home/custom-op# ls
BUILD  LICENSE  MANIFEST.in  Makefile  README.md  WORKSPACE  build_pip_pkg.sh  configure.sh  setup.py  tensorflow_zero_out  tf
root@52727958a85b:/home/custom-op# ./configure.sh
rm: cannot remove '.bazelrc': No such file or directory
using installed tensorflow
root@52727958a85b:/home/custom-op# bazel test ...
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
WARNING: /root/.cache/bazel/_bazel_root/f59710f949de61c873019b8044b9e9cf/external/local_config_tf/BUILD:3506:1: target 'libtensorflow_framework.so' is both a rule and a file; please choose another name for the rule
WARNING: /root/.cache/bazel/_bazel_root/f59710f949de61c873019b8044b9e9cf/external/local_config_tf/BUILD:5:12: in hdrs attribute of cc_library rule @local_config_tf//:tf_header_lib: file '_api_implementation.so' from target '@local_config_tf//:tf_header_include' is not allowed in hdrs
WARNING: /root/.cache/bazel/_bazel_root/f59710f949de61c873019b8044b9e9cf/external/local_config_tf/BUILD:5:12: in hdrs attribute of cc_library rule @local_config_tf//:tf_header_lib: file '_message.so' from target '@local_config_tf//:tf_header_include' is not allowed in hdrs
INFO: Analysed 5 targets (22 packages loaded).
INFO: Found 4 targets and 1 test target...
FAIL: //tensorflow_zero_out:zero_out_ops_py_test (see /root/.cache/bazel/_bazel_root/f59710f949de61c873019b8044b9e9cf/execroot/__main__/bazel-out/k8-fastbuild/testlogs/tensorflow_zero_out/zero_out_ops_py_test/test.log)
INFO: Elapsed time: 33.232s, Critical Path: 16.92s
INFO: 6 processes: 6 local.
INFO: Build completed, 1 test FAILED, 18 total actions
//tensorflow_zero_out:zero_out_ops_py_test                               FAILED in 3.0s
  /root/.cache/bazel/_bazel_root/f59710f949de61c873019b8044b9e9cf/execroot/__main__/bazel-out/k8-fastbuild/testlogs/tensorflow_zero_out/zero_out_ops_py_test/test.log

INFO: Build completed, 1 test FAILED, 18 total actions
root@52727958a85b:/home/custom-op# more /root/.cache/bazel/_bazel_root/f59710f949de61c873019b8044b9e9cf/execroot/__main__/bazel-out/k8-fastbuild/testlogs/tensorflow_zero_out/zero_out_ops_py_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tensorflow_zero_out:zero_out_ops_py_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/f59710f949de61c873019b8044b9e9cf/execroot/__main__/bazel-out/k8-fastbuild/bin/tensorflow_zero_out/zero_out_ops_py_test.runfiles/__main__/tensorfl
ow_zero_out/python/ops/zero_out_ops_test.py", line 23, in <module>
    from zero_out_ops import zero_out
  File "/home/custom-op/tensorflow_zero_out/python/ops/zero_out_ops.py", line 25, in <module>
    resource_loader.get_path_to_datafile('_zero_out_ops.so'))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/custom-op/tensorflow_zero_out/python/ops/_zero_out_ops.so: cannot open shared object file: No such file or directory
root@52727958a85b:/home/custom-op#
```

**Comment by yifeif** [comment]
Could you check if the py3 version of TensorFlow has actually been installed?

**Comment by zou000** [comment]
Yes. I did. To be 100% sure, here is the exact steps to repro this issue (I am using docker on MacOs, but I don't think it matters) :

```
docker pull tensorflow/tensorflow:custom-op
docker run -it tensorflow/tensorflow:custom-op /bin/bash
./configure.sh
bazel test ...
```

**Comment by zou000** [comment]
@yifeif any suggestions? technically I can build the pip package, install the package and then run the test, but it is a rather cumbersome way to run unittests.

**Comment by yifeif** [comment]
Need to investigate more on what has changed, but could you try changing get_path_to_datafile call in /usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/resource_loader.py to use _sys._getframe(2) instead of _sys._getframe(1).
depth 1 is pointing to where bazel is ran, depth 2 is pointing to bazel-out dir, where the .so is located.

**Comment by yifeif** [comment]
@zou000 I have updated the way import is done in the test in c681173edcc00ea6fb365914676ec6901ffb29e8 to have the correct call depths for bazel. Closing this issue. Let me know if you are still seeing it. Thanks!
