### ISSUE TITLE
Does anyone successfully compile and test "time_two_op" on the "2.1.0-custom-op-gpu-ubuntu16" image?

### ISSUE THREAD

**Issue by TCBocean** [tensorflow/custom-op#55]
My environment is
Ubuntu 18.04
(Do I need to provide another environment?)
I tried for a long time without successfully completing the test of time_two_op.
The initial problem was that nvcc couldn't find the fPIC option. This is because there is CFLAGS in NVCC, and the fPIC in CFLAGS did not add Xcompiler before, and nvcc couldn't find fPIC.
Later.
I encountered some problems. I forgot what changes I made, and finally I compiled the SO library.
The following are my compilation instructions and output:

> root@c2f387c31644:/working_dir/my_op# make time_two_gpu_only
2020-05-09 03:33:32.838500: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-09 03:33:32.839752: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-05-09 03:33:34.059140: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-09 03:33:34.060345: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
nvcc -std=c++11 -c -o tensorflow_time_two/python/ops/_time_two_ops.cu.o tensorflow_time_two/cc/kernels/time_two_kernels.cu.cc -I/usr/local/lib/python2.7/dist-packages/tensorflow_core/include -D_GLIBCXX_USE_CXX11_ABI=0 -O2 -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -L/usr/local/lib/python2.7/dist-packages/tensorflow_core -l:libtensorflow_framework.so.2 -x cu -Xcompiler -fPIC -DNDEBUG --expt-relaxed-constexpr

> root@c2f387c31644:/working_dir/my_op# make time_two_op
2020-05-09 03:34:06.279300: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-09 03:34:06.280573: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-05-09 03:34:07.469400: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-09 03:34:07.470612: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
g++ -I/usr/local/lib/python2.7/dist-packages/tensorflow_core/include -D_GLIBCXX_USE_CXX11_ABI=0 -O2 -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -o tensorflow_time_two/python/ops/_time_two_ops.so tensorflow_time_two/cc/kernels/time_two_kernels.cc tensorflow_time_two/cc/kernels/time_two.h tensorflow_time_two/cc/ops/time_two_ops.cc tensorflow_time_two/python/ops/_time_two_ops.cu.o -shared -L/usr/local/lib/python2.7/dist-packages/tensorflow_core -l:libtensorflow_framework.so.2  -D GOOGLE_CUDA=1  -I/usr/local/cuda/targets/x86_64-linux/include -L/usr/local/cuda-10.1/targets/x86_64-linux/lib -lcudart

> root@c2f387c31644:/working_dir/my_op# make time_two_test
2020-05-09 03:34:26.682548: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-09 03:34:26.683766: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-05-09 03:34:27.891841: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-09 03:34:27.893596: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
python tensorflow_time_two/python/ops/time_two_ops_test.py
2020-05-09 03:34:29.092042: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-09 03:34:29.093241: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Traceback (most recent call last):
  File "tensorflow_time_two/python/ops/time_two_ops_test.py", line 28, in <module>
    import time_two_ops
  File "/working_dir/my_op/tensorflow_time_two/python/ops/time_two_ops.py", line 25, in <module>
    resource_loader.get_path_to_datafile('_time_two_ops.so'))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /working_dir/my_op/tensorflow_time_two/python/ops/_time_two_ops.so: undefined symbol: _ZN10tensorflow7functor14TimeTwoFunctorIN5Eigen9GpuDeviceEiEclERKS3_iPKiPi
Makefile:42: recipe for target 'time_two_test' failed
make: *** [time_two_test] Error 1

It can be seen that there is nothing defined when loading SO finally.
Later, I tried to write a GPU OP, and the "undefined symbol" error appeared when loading the SO library.
And the example of zero_out Op can work normally

Whether or not --runtime = nvidia --privileged boot image will have this problem。I don't know how to solve it, can someone help me?

**Comment by TCBocean** [comment]
最后我在Ubuntu18.04 tfgpu2.1.0下编译了time_two_op，而没有使用docker
