### ISSUE TITLE
I am getting "undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb" error when trying to build the pip package

### ISSUE THREAD

**Issue by swaroop1904** [tensorflow/custom-op#72]
I followed the steps as mentioned in the README, 

```
docker run -it tensorflow/tensorflow:2.1.0-custom-op-gpu-ubuntu16 /bin/bash
git clone https://github.com/tensorflow/custom-op.git
cd custom-op
 ./configure.sh
 bazel build build_pip_pkg
 bazel-bin/build_pip_pkg artifacts
pip install artifacts/*.whl
cd ..
python -c "import tensorflow as tf;import tensorflow_zero_out;print(tensorflow_zero_out.zero_out([[1,2], [3,4]]))"
```

I get the following error when I try to import the installed package. 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_zero_out/__init__.py", line 19, in <module>
    from tensorflow_zero_out.python.ops.zero_out_ops import zero_out
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_zero_out/python/ops/zero_out_ops.py", line 25, in <module>
    resource_loader.get_path_to_datafile('_zero_out_ops.so'))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python2.7/dist-packages/tensorflow_zero_out/python/ops/_zero_out_ops.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
```

I tried to build with the Makefile as well but I am facing the same issue.

**Comment by swaroop1904** [comment]
This is happening only since yesterday and I was able to build it without any issues before that.

**Comment by roymiles** [comment]
Any update on this issue? did you manage to fix it? 
I was able to build a custom-op with tensorflow 2.0.0, but I get this error with tf 2.2.0. Unfortunately, I need 2.2.0 for the GPU profiler.

**Comment by swaroop1904** [comment]
For me, python2 was getting picked by default. So after updating 

```python setup.py bdist_wheel > /dev/null ```
to 
```python3 setup.py bdist_wheel > /dev/null```

in build_pip_pkg.sh it worked fine.
